### ISSUE TITLE
Ignore expressions in quotes

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-expressions#101]
Imagine we run PostHTML with `{ locals: { foo: 'bar' } }` on this HTML:

```html
<p>{{ 1 === 1 ? '{{ foo }}' : 'false' }}</p>
```

Normally, you'd expect this to be output:

```html
<p>{{ foo }}</p>
```

... however, I think the plugin tries to parse `'{{ foo }}'` and it fails with a `SyntaxError`:

```sh
SyntaxError {
  message: 'Invalid or unexpected token',
}
```

I think `posthtml-expressions` should not try to parse 'expressions' inside quotes, these should be simply treated as strings and parsing should skip them.

**Comment by Scrum** [comment]
@cossssmin Hi
The point is finding part of the expression and in your case it turns out
``` js
1 === 1? '{{foo
```
If you write a regex that will search for an expression with quotes taken into account, then the question remains unresolved with an expression in attributes like
```html
<p class="{{ dynamicClass }}">
```
