### ISSUE TITLE
Option to disable @{{ }}

### ISSUE THREAD

**Issue by alker0** [posthtml/posthtml-expressions#106]
Importing CDN assets, it often needs the `@x.x.x` format for specifying the version. So I want to pass the asset version to `locals` without `@`, and use `@{{ }}` syntax in html.

like this:
```javascript
postHtml(
  expressions({
    locals: {
      foundationVersion: '6.6.3',
    },
  }),
).process(`

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@{{ foundationVersion }}/dist/css/foundation.min.css">

<script src="https://cdn.jsdelivr.net/npm/foundation-sites@{{ foundationVersion }}/dist/js/foundation.min.js"></script>

`);
```

It outputs:
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites{{ foundationVersion }}/dist/css/foundation.min.css">

<script src="https://cdn.jsdelivr.net/npm/foundation-sites{{ foundationVersion }}/dist/js/foundation.min.js"></script>
```
This is invalid CDN path.

So currently, it must move `@` to `locals` for all CDN assets. I think it would be great if there is a  option to disable `@{{ }}`.

**Comment by cossssmin** [comment]
Use the `<raw>` tag, or define custom delimiters.

**Comment by alker0** [comment]
I want an output like:
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/css/foundation.min.css">

<script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/js/foundation.min.js"></script>
```
So it needs away to replace variables even when using `@` on the left side of delimiters.

Is there how to transform `foundation-sites@{{ foundationVersion }}` to `foundation-sites@x.x.x`?

**Comment by Scrum** [comment]
I think you'd better transfer the full URL for the resource in the data. you still look for a version for it

```html


<script src="{{ fundation-site-js-url }}"></script>
```

and even better, immediately generate a list of static resources and display them via `each`

```html
<each loop="cssURL in arrayCSS">
  <link rel="stylesheet" href="{{ cssURL }}">
</each>

<each loop="jsURL in arrayJS">
<script src="{{ jsURL }}"></script>
</each>
```

**Comment by alker0** [comment]
Why did not I think of that way. I will try it immediately. Thank you.
