### ISSUE TITLE
strictMode: loops still throw error if target is not object

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-expressions#107]
https://github.com/posthtml/posthtml-expressions/blob/5a883311929ad53b44f3b51b9bd05af7f1eb0ef2/lib/index.js#L346-L349

@Scrum I think we could do a check for `strictMode` here?

```diff
- if (typeof target !== 'object') {
+ if (typeof target !== 'object' && opts.strictMode) {
```

Something like this will fail if `items` is `undefined` (or not an object for that matter), even though `strictMode` is set to `false`:

```html
<if condition="items && items.length > 0">
  <each loop="item, key in items">
    {{ item.text }}
  </each>
</if>
```

Ref: https://github.com/maizzle/framework/issues/354

**Comment by cossssmin** [comment]
Same here:

https://github.com/posthtml/posthtml-expressions/blob/5a883311929ad53b44f3b51b9bd05af7f1eb0ef2/lib/index.js#L391-L394

**Comment by cossssmin** [comment]
Hmm, just realized that this:

https://github.com/posthtml/posthtml-expressions/blob/5a883311929ad53b44f3b51b9bd05af7f1eb0ef2/lib/index.js#L344

... could use a try/catch to avoid breaking when evaluating code fails:

```diff
- const target = vm.runInContext(loopParams.expression, ctx)
+ const target = () => {
+   try {
+     return vm.runInContext(loopParams.expression, ctx)
+   } catch() {
+     return ctx
+   }
+ }
```

This way, we'd always return the `ctx` object, either ran in context or the original.

I think this might have to depend on `strictMode` though? I mean, the normal behavior should be "strict" and invalid code should break things, then `strictMode: false` could prevent it:

```js
const target = () => {
  if (strictMode) {
    return vm.runInContext(loopParams.expression, ctx)
  } 
  else {
    try {
      return vm.runInContext(loopParams.expression, ctx)
    } catch() {
      return ctx
    }
  }
}
```

What do you think @Scrum?

**Comment by Scrum** [comment]
@cossssmin publish v1.6.2

**Comment by schirliuradu** [comment]
Still having issues with each loops, using posthtml inside maizzle email templating framework. 

I'll leave a link to a repo that reproduces the bug [here](https://github.com/schirliuradu/posthtml-each-loop-bug).

It would be enough to add extra condition here ``( && opts.strictMode )``
https://github.com/posthtml/posthtml-expressions/blob/bc94d52d3b496ded658cdc758eebe9cbed0ebc62/lib/index.js#L354

Maybe there would be even a better solution, but this seems to work as it should work.

**Comment by cossssmin** [comment]
@Scrum please consider @schirliuradu's comment above after merging #109, maybe we could include it and release a feature version.

**Comment by Scrum** [comment]
> I'll leave a link to a repo that reproduces the bug [here](https://github.com/schirliuradu/posthtml-each-loop-bug).

i couldn't deploy your project to get error
![Screenshot 2020-12-02 at 10 29 46](https://user-images.githubusercontent.com/2789192/100842161-769b8680-3489-11eb-8d5a-1d717c1b9ca2.png)

**Comment by Scrum** [comment]
> It would be enough to add extra condition here `( && opts.strictMode )`

@cossssmin I'll add this, but I need to understand the case to write tests for this.

**Comment by Scrum** [comment]
> > It would be enough to add extra condition here `( && opts.strictMode )`
> 
> @cossssmin I'll add this, but I need to understand the case to write tests for this.

https://github.com/posthtml/posthtml-expressions/pull/110/commits/fc5662bff86f130506281fcaa12e5936ee8340a9

**Comment by schirliuradu** [comment]
Ok, i'll try to send a link to another repo, a bit later @Scrum

**Comment by Scrum** [comment]
> Ok, i'll try to send a link to another repo, a bit later

I made a fix on `posthtml-expressions` try reinstall and try
