### ISSUE TITLE
Load local data from <script data> tag in html file

### ISSUE THREAD

**Issue by Sulaymon-dev** [posthtml/posthtml-expressions#117]
Hi, in tailwindcss framework "Adam Wathan" work with posthtml and this like workflow

![posthtml](https://user-images.githubusercontent.com/40419449/123032770-faa26500-d3ff-11eb-9e6b-66477d0e7a22.png)

it's was super helpful for automating coding

**Comment by Scrum** [comment]
@Sulaymon-dev  Hello, do you want to clarify? where and where to download? and how to use it?

It will be good if you describe an example in which you indicate what you are doing and what you expect to receive.

**Comment by Sulaymon-dev** [comment]
"Adam Wathan" creator of Tailwindcss use it livestream on youtube ...
He use posthtml for templating 
His workflow - https://youtu.be/oQhVNja7Trw?t=270
He say "We using PostHTML for templating" https://youtu.be/oQhVNja7Trw?t=410

it's really super easy for creating html themes without any template engine, frameworks and ...

**Comment by Scrum** [comment]
Thank you, I'll take a look at this material.
