### ISSUE TITLE
Remove <script locals> after build html.

### ISSUE THREAD

**Issue by s-kobets** [posthtml/posthtml-expressions#120]
Hi, thank you to plugin, but I don't understand, why `<script locals>` don't removed after build html?
before 
```javascript
<script locals>
  module.exports = {
    name: 'Scrum'
  }
</script>

<div>My name: {{name}}</div>
```

after
```javascript
<script locals>
  module.exports = {
    name: 'Scrum'
  }
</script>

<div>My name: Scrum</div>
```

I think <script locals> this artefact and this should remove after build or configuration this behavior. What do you think?

**Comment by gormster** [comment]
+1. This should at least be an option, and IMO it should probably default to true.

**Comment by Scrum** [comment]
You're welcome. Now you can use the option `removeScriptLocals` since version `1.9.0`
