### ISSUE TITLE
 How to check if a variable is set?

### ISSUE THREAD

**Issue by thewebartisan7** [posthtml/posthtml-expressions#124]
Suppose we have a variable for set body class.
In case we don't pass any variable as body class I get `class="undefined"`

How to check if variable is set?

Like:

```
<body class="{{ if(bodyClass) bodyClass }}">
or
<body class="{{ bodyClass ? bodyClass : 'default' }}">
```

**Comment by Scrum** [comment]
Now you'd better resort to constructing https://github.com/posthtml/posthtml-expressions#conditionaltags. In the future, I'll see what can be done for such expressions. Thank you for bringing this to our attention.

**Comment by thewebartisan7** [comment]
Thanks. I already saw conditional tags, however it's messed to do this for every variable, like html dir attribute, head title tag, several classes, etc.

**Comment by cossssmin** [comment]
```
<body class="{{ bodyClass || 'default' }}">
```

Where `'default'` can be an empty string `''` in order to output `<body class="">`.

**Comment by thewebartisan7** [comment]
> Same as your other examples:
> 
> ```
> <body class="{{ bodyClass || 'default' }}">
> ```
> 
> Where `'default'` can be an empty string `''` in order to output `<body class="">`.

Thanks for your reply. I have already try this, but this works only when bodyClass is defined, even empty.

When it's not defined, the output is like:

```
{{ bodyClass || 'default' }} 
```

Or sometimes even there is error undefined variable.

**Comment by thewebartisan7** [comment]
Component:

```
<div class="{{ maybeUndefined || 'is undefined' }}">
  {{ maybeUndefined || 'is undefined' }}
</div>
```

Usage:
```
<h1>test2</h1>

<include src="components/test.html"></include>
```

Output:

<img width="451" alt="Screenshot 2022-04-27 at 09 34 33" src="https://user-images.githubusercontent.com/57477934/165466043-259e430f-72b6-4f15-a368-b60c23c73da9.png">

**Comment by thewebartisan7** [comment]
I found a way to handle this:

```html
<body class="{{ typeof bodyClass !== 'undefined' ? bodyClass : 'default' }}">
```
