### ISSUE TITLE
Each loop not working

### ISSUE THREAD

**Issue by thewebartisan7** [posthtml/posthtml-expressions#125]
In read me there is this example:

```html
<each loop="item in [1,2,3]">
  <p>{{ item }}</p>
</each>
```

But it seem not working..
Only when passing array via locals.

Also adding below not working:

```html
<script locals>
	module.exports = {
		inputs: [2,3,4,5,6]
	}
</script>

<each loop="item in inputs">
  <p>{{ item }}</p>
</each>
```

**Comment by cossssmin** [comment]
All loop tests pass and that works fine, can you please share a repository that reproduces the issue?

**Comment by thewebartisan7** [comment]
> All loop tests pass and that works fine, can you please share a repository that reproduces the issue?

I can't find in your test the example of this way to define locals:

```
<script locals>
  module.exports = {
    name: 'Scrum'
  }
</script>

<div>My name: {{name}}</div>
```

Because this is what I am trying. 

Should I prepare a repo with this?

I am using posthtml-loader with webpack.

**Comment by cossssmin** [comment]
It's here:

https://github.com/posthtml/posthtml-expressions/blob/260a048538e78f79d9d62e15961ecd6f4129d399/test/test-locals.js#L34-L40

> Should I prepare a repo with this?

Yes please if you can, thanks.
