### ISSUE TITLE
Broken links in package.json

### ISSUE THREAD

**Issue by mrmlnc** [posthtml/posthtml-expressions#22]
## Problem

Your `package.json` has broken links.

## Details

Current repository: `posthtml-expressions`. Links in `package.json` reference to `posthtml-exp`.

And when I click on links on npmjs.com I see a sad wombat. I don't like seeing a sad wombat 😭 

## Error log

```
not found
https://www.npmjs.com/github.com/posthtml/posthtml-exp does not exist. time to go outside.
```

**Comment by michael-ciniawsky** [comment]
👍 on the list for a long time, will be fixed with the other bug in next release as `posthtml-expressions`
