### ISSUE TITLE
Remove options.conditionals, options.loops, options.scope (tags)

### ISSUE THREAD

**Issue by michael-ciniawsky** [posthtml/posthtml-expressions#30]

**Comment by michael-ciniawsky** [comment]
👍 (yes) / 👎(no)  via comment reactions pls 😛 

Concerns blow 😎

**Comment by jescalan** [comment]
So there would be no way to run a loop or conditional? Wouldn't this be a major important feature lost for pretty much all users of this plugin?

**Comment by michael-ciniawsky** [comment]
@jescalan I have to change the tilte :). Nope it's just about the options to define our own tags for conditionals, loops, scope and use the default ones

**Comment by jescalan** [comment]
What is the advantage of removing extra customizability?

**Comment by michael-ciniawsky** [comment]
> What is the advantage of removing extra customizability?

removing extra customizability ? :D, customize delimiters in terms of style ok, there are many different already in the wild, so when someone wants to replace his current templating solution with posthtml-expressions he can stick with his current style. But imo its better to fixate the logical tags and therefore remove the options to do so aswell. What is a reasonable usecase to overriding them brings 'benefits' / better / easier usage?

**Comment by jescalan** [comment]
Tag conflicts. The `if`, `else`, `each` etc. are all custom elements that we replace. If there is any other type of tool that uses these custom elements instead of what we replace them with, you'd be out of luck unless you could switch up the names.

**Comment by mrmlnc** [comment]
I think that is bad idea, because, for example, I use `for` for `loops` 😄

**Comment by michael-ciniawsky** [comment]
@jescalan  @mrmlnc Alright 😞 , personally still not convinced if it's really necessary/valuable 😛 , but not my sole decision, let's keep it for now.
