### ISSUE TITLE
Switch

### ISSUE THREAD

**Issue by michael-ciniawsky** [posthtml/posthtml-expressions#33]
```html
<switch expression="">
  <case n="">
  <case n="">
  <default>
</switch>
```

**Comment by mrmlnc** [comment]
I'm not a fan of big logic in HTML, but it is possible. I'll take a look on this feature soon.

**Comment by michael-ciniawsky** [comment]
yep maybe unnessecary, by no means urgent or a 'killer feature', but imo nice-to-have nevertheless
