### ISSUE TITLE
Messages 

### ISSUE THREAD

**Issue by michael-ciniawsky** [posthtml/posthtml-expressions#37]
## Problem

The current implementation overrides `tree.messages`and results in `result.messages === undefin
ed`

## Details

Seems to be caused by the custom `walk` function  

## Issue [ Code ]

```bash
$ git clone https://github.com/michael-ciniawsky/posthtml
$ git checkout messages
```

## Environment

| OS              | Node      | npm       | PostHTML  |
|:---------------:|:---------:|:---------:|:---------:|
| macOS 10.12.2 | 7.3.0 | 3.10.10 |`michael-ciniawsky/posthtml.git#messages`|

**Comment by mrmlnc** [comment]
Because we use `throw` instead of `tree.messages` 😄

**Comment by michael-ciniawsky** [comment]
@mrmlnc :trollface: 😛 

 Sure but it overrides `tree.messages` completely so all messages from other plugins used before `posthtml-expressions` are lost at the moment 😭

**Comment by andreyvolokitin** [comment]
@michael-ciniawsky could this be a suitable fix? https://github.com/andreyvolokitin/posthtml-expressions/commit/4b65003ca009b24876e5ebf655af87eba0b1b97e
