### ISSUE TITLE
[feat]: Attributes

### ISSUE THREAD

**Issue by michael-ciniawsky** [posthtml/posthtml-expressions#38]
## Problem

Implement logic via attributes

### Conditionals

```html
<div if='condition'>
   <div elseif='condition'></div>
   <div else><div>
</div>
```
### Loops

```html
<ul for='item in items'>
  <li>{{ item }}</li>
</ul>
```

### Switch

```html
<div switch='cases'>
   <div case=''></div>
   <div case=''></div>
   <div default></div>
</div>
```

### Scope

```html
<div scope="">
  ...
</div>
```

**Comment by jescalan** [comment]
why?

**Comment by michael-ciniawsky** [comment]
cleaner markup, similiar to e.g Vue's Template Syntax, tags usage should stay of course

**Comment by jescalan** [comment]
I still don't understand why this would be worth doing at all. It's not cleaner, it's actually more markup and characters to do it this way. But whatever you feel!

**Comment by michael-ciniawsky** [comment]
> It's not cleaner

### Tag

```html
<ul>
  <each loop="item in items">
     <li>{{ item ))</li>
  </each>
</ul>
```

### Attributes

```html
<ul for="item in items">
  <li>{{ item ))</li>
</ul>
```

? :)

If it is to difficult or needs to much additional extra logic to implement, then ok it's maybe not really worth the change/extra work.

**Comment by xakdog** [comment]
**for** and **scope** looks nice. But **conditionals** loses indentation and seems to be very unclear.

**Comment by jescalan** [comment]
If you did implement it like this, and the user needed a transparent block tag not explicitly attached to an existing tag in the DOM, which is a use case and [implemented by vue's syntax](https://vuejs.org/v2/guide/list.html#Template-v-for), you'd need to make an extra element available to serve as the transparent block, the same way `each` works now.

**Comment by tresdin** [comment]
I think the loop syntax would be cleaner this way.
```<for var="key, value" in="array">
  <p>Hello World!</p>
</for>```

and in SugarML, it will look like
```for(var="value, key" in="array")
  p Hello World!```
