### ISSUE TITLE
[fix]: Expressions doesn't work with `posthtml-extend`

### ISSUE THREAD

**Issue by mikestopcontinues** [posthtml/posthtml-expressions#53]
## Problem

`posthtml-extend` updates the tree to be contained within the extended page. For some reason, this breaks `posthtml-expressions`. But it would be awesome to both use the plugins together, as well as use expressions logic in the extended template.

## Reproduction

Two different issues:

1. Try to use expressions within a template that extends another.
2. Try to use expressions within a template that is extended by another.

Expressions work so long as you don't try to extend the current template.

**Comment by GitScrum** [comment]
@mikestopcontinues Hi, thanks for your feedback, I'll check it out soon.

**Comment by GitScrum** [comment]
@mikestopcontinues wait merge and publish [PR](https://github.com/posthtml/posthtml-extend/pull/9)

**Comment by mikestopcontinues** [comment]
Thanks, @GitScrum! You rock!

**Comment by michael-ciniawsky** [comment]
@mikestopcontinues Can you show your current `posthtml` config and the plugin order ?

**Comment by mikestopcontinues** [comment]
Sure!

```js
posthtml([
  extend({root}),
  modules({root}),
  include({root}),
  expressions(),
]);
```

**Comment by GitScrum** [comment]
Now you need set extend options `plugins` when call `expressions`
```js
posthtml([
  extend({root, plugins: [expressions()]}),
  modules({root}),
  include({root}),
  expressions(),
]);
```

**Comment by mikestopcontinues** [comment]
Ok, thanks!

**Comment by GitScrum** [comment]
@mikestopcontinues wait publish in npm )

**Comment by michael-ciniawsky** [comment]
Does `posthtml-extend` (not too familiar with it 😛 ) not also `extend the `tree` (AST), so `posthtml-expressions` should normally work if it is used **after** `posthtml-extend` ? We use a custom `walk` `{Function}` in `posthtml-expressions` atm, maybe there is something lost during interpolation ?

**Comment by GitScrum** [comment]
@mikestopcontinues Done! enjoy, and close this issue if all good.

**Comment by mikestopcontinues** [comment]
Thanks!
