### ISSUE TITLE
[Feature Request] Loop-related variables

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-expressions#65]
Would you accept a PR that adds a `loop` object to the `locals`, when inside a loop?

It would expose the following object:

```
loop: {
  index: 0,
  remaining: 2,
  first: true,
  last: false,
  length: 3
}
```

So you could use it inside a loop, like this:

```html
<each loop='value, key in items'>
  <tr class="{{ loop.index % 2 == 0  ? 'even' : 'odd' }}">
    <td>{{ key }}: {{ value }} {{ loop.first ? 'is first' : '' }}</td>
    
    <if condition="loop.last">
      <td class="last"></td>
    </if>
  </tr>
</each>
```

Of course, it would be available when looping over both arrays and objects.

Could be useful for various things, but I've frequently used it for:

- outputting content based on where we are in the loop
- building paginations

---

This is inspired by the [for loop in Nunjucks](https://mozilla.github.io/nunjucks/templating.html#for).

I already have it working locally, so if this is something you also find useful, I can do a PR.

**Comment by anikethsaha** [comment]
is it similar to [this](https://github.com/posthtml/posthtml-expressions#loops)

**Comment by cossssmin** [comment]
It's an object with information about the loop currently being executed.

- `index` - the current iteration of the loop (0 indexed)
- `remaining` - number of iterations until the end (0 indexed)
- `first` - boolean indicating if it's the first iteration
- `last` - boolean indicating if it's the last iteration
- `length` - total number of items

**Comment by anikethsaha** [comment]
having `index` and `length` will fix the need of rest three right !

also, you want to add this in existing loop feature ?

**Comment by cossssmin** [comment]
> having `index` and `length` will fix the need of rest three right !

I don't understand what you mean. I think we're hitting a language barrier, so might as well just do the PR and show you the code :)

**Comment by anikethsaha** [comment]
I meant, having `index` and `length` property is enough right cause with these two, we can calculate the rest three !

and, this plugin already has loops concept so I am confused is it something you want to add on top of it or want to create a separate loop feature ? if separate , how this will be different from the old one ?

**Comment by cossssmin** [comment]
> I meant, having `index` and `length` property is enough right cause with these two, we can calculate the rest three !

The point is to provide local loop data for the user and not make them calculate it themselves.

If you want the user to calculate it, then this feature wouldn't even be needed, because you can currently get the `index` and calculate the `length` yourself, too.

> and, this plugin already has loops concept so I am confused is it something you want to add on top of it or want to create a separate loop feature ? if separate , how this will be different from the old one ?

It's not a separate loop, this just exposes a `loop` object when you're inside the loop. The plugin's current looping functionality is not changed.

**Comment by anikethsaha** [comment]
Ohh let me know if I get it correctly, 

this is kind of metadata for the loop tag right ?
this plugin will calculate those props (`first`, `second`, `last` etc) for you and we can access this inside of loop tag using `loop` local object.! we don't have to write the loop local object manually , this plugin will inject those 

right ?

**Comment by cossssmin** [comment]
Yes, exactly, so you can access those props from a local `loop` object.

Maybe my example was too complicated, here's a simple one:

```html
<each loop='value, key in items'>
    There are {{ loop.remaining }} iterations remaining
</each>
```

**Comment by anikethsaha** [comment]
seems like a good enhancement !.  👍 

cc @Scrum

**Comment by Scrum** [comment]
Looks good. 

How will this work with nested loops? 

```html
<each loop='value, key in items'>
    There are {{ loop.remaining }} iterations remaining
    <each loop='value, key in items'>
      {{ loop.remaining }} // - ???  how to get top `loop` 
    </each>
</each>
```

**Comment by cossssmin** [comment]
Each loop would give access to its own metadata; it would not have access to its parent metadata. Looking at other templating languages, I see they do the same thing...

**Comment by cossssmin** [comment]
@Scrum would it perhaps be useful if loops also accepted a `locals=""` attribute, so they can pass down variables? This way, what you're asking abot the top loop would probably be possible.

**Comment by cossssmin** [comment]
So what I mean is:

```html
<each loop='value, key in items'>
    There are {{ loop.remaining }} iterations remaining
    <each loop='value, key in items' locals="{parentLoop: loop}">
      {{ parentLoop.remaining }}
    </each>
</each>
```

Would be useful in general, as you'd be able to send data from a parent to any nested child loop.
