### ISSUE TITLE
Can't use together with expressions plugin

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-expressions#68]
Found a weird issue: if you use `posthtml-expressions` together with this plugin, it will fail with either a `TypeError` or a `ReferenceError` (depending on which one you add to the plugins array first).

So this setup:

```js
const html = `<fetch url="https://jsonplaceholder.typicode.com/users/1">
  {{ response.name }}
</fetch>`

posthtml([
    require('posthtml-expressions')({ locals: { var: 'test' } }),
    require('posthtml-fetch')()
  ])
    .process(html)
    .then(result => result.html)
    .catch(error => { throw error })
```

Fails with `ReferenceError: response is not defined`

If you switch plugin order, you get `TypeError: nodes.reduce is not a function`.

_However_, if you skip expression parsing with `@{{ }}`, it works 😵

```html
<fetch url="https://jsonplaceholder.typicode.com/users/1">
  @{{ response.name }}
</fetch>
```

... that correctly outputs 'Leanne Graham' and the build doesn't break.

@Scrum any ideas? Is my setup wrong or is there a bug in the plugin?

**Comment by Scrum** [comment]
@cossssmin I moved it because this is a package error `posthtml-expression`

**Comment by cossssmin** [comment]
Ah, ok, let me know if you need anything else from my side 👍

**Comment by Scrum** [comment]
@cossssmin publish v1.3.1
