### ISSUE TITLE
locals can only be JSON string

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-expressions#70]
Consider `{{ title }}` is a string equal to `test`.

```html
<!-- include.html -->
<p>The title in the include is: {{ title }}</p>
```

```html
<!-- test.html -->
<p>The title is: {{ title }}</p>
<include src="include.html" locals="{{ title }}"></include>
```

Result: `SyntaxError: Unexpected token { in JSON at position 1`

These won't work, either:

```html
<include src="include.html" locals=locals='{"title": {{ title }} }'></include>

<include src="include.html"  locals='{{ {"title": title } }}'></include>

<include src="include.html"  locals='{"title": title }'></include>
```

Would be awesome if you could pass expressions variables inside the `locals=""` attribute - sometimes you need to pass in something that has a dynamic/computed value, so you can't write it out by hand.

Any ideas?

**Comment by Scrum** [comment]
@cossssmin I tried to understand the reason for a long time and finally found it #71

**Comment by Scrum** [comment]
@cossssmin publish v1.3.2, The only thing that needs to be done since execution of plugins is asynchronous, you need to finish the option `after`, `before` in `posthtml-fetch` which will add plugins before and after the expression plugin
![Screenshot 2020-04-10 at 13 32 42](https://user-images.githubusercontent.com/2789192/78984779-c8288700-7b2f-11ea-8d80-f7a30473797e.png)

**Comment by cossssmin** [comment]
Awesome, will have a look and get back to you. Will also need to implement this somehow in `posthtml-modules` ('somehow' because it's not using the same codebase...)

**Comment by cossssmin** [comment]
Hmm, just tried this with `posthtml-include` and it still fails?

```html
<!-- page is an object I already have -->
<include src="footer.html" locals="page">
```

```html
<!-- footer.html -->
<div>Copyright {{ year }}</div>
```

```sh
SyntaxError: Unexpected token p in JSON at position 0 at JSON.parse
```

**Comment by Scrum** [comment]
@cossssmin Yes, in this case, you need to check whether the string is of the form `json`, 

the correct result for you then will be
```html
<div>Copyright undefined</div>
```

**Comment by cossssmin** [comment]
I'm not sure I understand, how can someone pass in that `page` object to that include?
