### ISSUE TITLE
loop - input.search is not a function

### ISSUE THREAD

**Issue by philerck** [posthtml/posthtml-expressions#93]
## Problem

I want to use the loop with posthtml-cli an d get the Error: input.search is not a function

## Details

My npm-Script:
"build:html": "posthtml -c posthtml.json"

This is may posthtml.json Config File
```
{
  "input": "src/views/**/*.html",
  "output": "dist",
  "plugins": {
    "posthtml-modules": {
      "root": "./src/views",
      "initial": true
    },
    "htmlnano": {},
    "posthtml-expressions": {
      "locals": {
        "items": [
          "foo",
          "bar"
        ],
        "className": "intro",
        "name": {
          "vorname": "Max",
          "nachname": "Mustermann"
        }
      }
    }
  }
}
```
My loop test file is in src/views

about.html
```
<each loop="item in items">
      <p>{{ item }}</p>
    </each>
```

## Error Logs

TypeError: input.search is not a function
    at parseLoopStatement (C:\xampp\htdocs\npmscriptstest\node_modules\posthtml-expressions\lib\loops.js:15:32)
    at C:\xampp\htdocs\npmscriptstest\node_modules\posthtml-expressions\lib\index.js:326:26
    at Array.reduce (<anonymous>)
    at walk (C:\xampp\htdocs\npmscriptstest\node_modules\posthtml-expressions\lib\index.js:169:27)
    at C:\xampp\htdocs\npmscriptstest\node_modules\posthtml-expressions\lib\index.js:206:22
    at Array.reduce (<anonymous>)
    at walk (C:\xampp\htdocs\npmscriptstest\node_modules\posthtml-expressions\lib\index.js:169:27)
    at C:\xampp\htdocs\npmscriptstest\node_modules\posthtml-expressions\lib\index.js:206:22
    at Array.reduce (<anonymous>)
    at walk (C:\xampp\htdocs\npmscriptstest\node_modules\posthtml-expressions\lib\index.js:169:27)

## Environment

Please provide information about your environment.

| OS              | Node      | npm       | PostHTML  |
|:---------------:|:---------:|:---------:|:---------:|
| Windows 10 | 12.16.2 | 6.14.5 | 0.13.1 |

**Comment by Scrum** [comment]
@philerck Hi, optimizer `htmlnano` must be used at the end of the list of plugins.

**Comment by Scrum** [comment]
The problem exists, it is associated with the normalization of the tree at the output.

**Comment by Scrum** [comment]
@philerck Update the package `posthtml-expressions` up to version 1.4.5, use the configuration for `posthtml.json` as I described above, enjoy

**Comment by philerck** [comment]
Hey @Scrum, thanks for the fast answer. Changed my config file and now its working. Thank you very much. Also for the awesome Plugin. One step further from nunjucks to posthtml.
