### ISSUE TITLE
Directives Are Ignored

### ISSUE THREAD

**Issue by trisys3** [posthtml/posthtml-expressions#97]
## Problem

Briefly describe the issue you are experiencing (or the feature you want to see
added to the plugin). Tell us what you were trying to do and what happened
instead. Remember, this is _not_ a place to ask questions. For that, go to
http://gitter.im/posthtml/posthtml

Directives seem to be completely ignored by this plugin.

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Error Logs

Create a [gist](https://gist.github.com) which is a paste of your **full**
logs(_result.tree_ (PostHTML Tree), _result.html_ (HTML)), and link them here.
Do **not** paste your full logs here, as it will make this issue long and hard
to read! If you are reporting a bug, **always** include logs!

## Issue [ Code ]

Please remember that, with sample code; it's easier to reproduce bug and much
faster to fix it.

Please refer to a simple code example.

```
const posthtml = require('posthtml');
const expressions = require('posthtml-expressions');

const text = '<?php echo $myVar; ?>';

const opts = {
    sync: true,
    directives: [{
        name: '?php',
        start: '<',
        end: '>',
    }],
};

const {html} = posthtml().process(text, opts);
console.log(html); // '<?php echo $myVar; ?>';

const {html} = posthtml([expressions()]).process(text, opts);
console.log(html); // '';
```

## Environment

Please provide information about your environment.

| OS              | Node      | npm       | PostHTML  |
|:---------------:|:---------:|:---------:|:---------:|
| CentOS 7.7 | 13.14.0 | 6.14.8 | 0.13.3 |

**Comment by Scrum** [comment]
@trisys3 publish v1.4.7
